/** @type {import('@commitlint/types').UserConfig} */
module.exports = {
  extends: ['@commitlint/config-conventional'],
  rules: {
    'type-enum': [
      2,
      'always',
      [
        'feat',
        'fix',
        'perf',
        'refactor',
        'docs',
        'test',
        'build',
        'ci',
        'chore',
        'revert',
        'style',
      ],
    ],
    'scope-enum': [
      1,
      'always',
      [
        'gateway',
        'auth',
        'booking',
        'hotel',
        'room',
        'pricing',
        'payment',
        'finance',
        'housekeeping',
        'maintenance',
        'notification',
        'review',
        'reporting',
        'web',
        'admin',
        'shared',
        'contracts',
        'infra',
        'ci',
        'deps',
        'docs',
        'release',
      ],
    ],
    'subject-case': [2, 'never', ['upper-case', 'pascal-case']],
    'header-max-length': [2, 'always', 100],
    'body-max-line-length': [1, 'always', 120],
  },
};
