/**
 * Machine-readable error codes. Every service returns one of these in the
 * standard error envelope so clients can branch on `error.code` rather than
 * pattern-matching human-readable messages.
 */
export const ErrorCode = {
  // ---- Generic (4xx) ----
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',

  // ---- Auth ----
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_DISABLED: 'ACCOUNT_DISABLED',
  EMAIL_NOT_VERIFIED: 'EMAIL_NOT_VERIFIED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_REVOKED: 'TOKEN_REVOKED',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  EMAIL_ALREADY_REGISTERED: 'EMAIL_ALREADY_REGISTERED',

  // ---- Inventory & booking ----
  ROOM_NOT_AVAILABLE: 'ROOM_NOT_AVAILABLE',
  ROOM_TYPE_SOLD_OUT: 'ROOM_TYPE_SOLD_OUT',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  STAY_TOO_LONG: 'STAY_TOO_LONG',
  OCCUPANCY_EXCEEDED: 'OCCUPANCY_EXCEEDED',
  INVALID_BOOKING_TRANSITION: 'INVALID_BOOKING_TRANSITION',
  BOOKING_NOT_CANCELLABLE: 'BOOKING_NOT_CANCELLABLE',

  // ---- Payments ----
  PAYMENT_DECLINED: 'PAYMENT_DECLINED',
  PAYMENT_ALREADY_CAPTURED: 'PAYMENT_ALREADY_CAPTURED',
  REFUND_EXCEEDS_CAPTURE: 'REFUND_EXCEEDS_CAPTURE',
  CURRENCY_MISMATCH: 'CURRENCY_MISMATCH',

  // ---- Platform (5xx) ----
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  UPSTREAM_UNAVAILABLE: 'UPSTREAM_UNAVAILABLE',
  UPSTREAM_TIMEOUT: 'UPSTREAM_TIMEOUT',
  CIRCUIT_OPEN: 'CIRCUIT_OPEN',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

/** Canonical HTTP status for each code, so mapping never drifts per service. */
export const ERROR_STATUS: Readonly<Record<ErrorCode, number>> = {
  VALIDATION_FAILED: 400,
  UNAUTHENTICATED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  RATE_LIMITED: 429,
  IDEMPOTENCY_KEY_REUSED: 409,

  INVALID_CREDENTIALS: 401,
  ACCOUNT_LOCKED: 423,
  ACCOUNT_DISABLED: 403,
  EMAIL_NOT_VERIFIED: 403,
  TOKEN_EXPIRED: 401,
  TOKEN_REVOKED: 401,
  REFRESH_TOKEN_REUSED: 401,
  EMAIL_ALREADY_REGISTERED: 409,

  ROOM_NOT_AVAILABLE: 409,
  ROOM_TYPE_SOLD_OUT: 409,
  INVALID_DATE_RANGE: 400,
  STAY_TOO_LONG: 400,
  OCCUPANCY_EXCEEDED: 400,
  INVALID_BOOKING_TRANSITION: 409,
  BOOKING_NOT_CANCELLABLE: 409,

  PAYMENT_DECLINED: 402,
  PAYMENT_ALREADY_CAPTURED: 409,
  REFUND_EXCEEDS_CAPTURE: 409,
  CURRENCY_MISMATCH: 400,

  INTERNAL_ERROR: 500,
  UPSTREAM_UNAVAILABLE: 503,
  UPSTREAM_TIMEOUT: 504,
  CIRCUIT_OPEN: 503,
};

export function httpStatusFor(code: ErrorCode): number {
  return ERROR_STATUS[code] ?? 500;
}
